# define constants value
LUA = 'LUA'
CAFE = 'CAFE'
CAM = 'CAM'
XOAI = 'XOAI'
DUA_HAU = 'DUA_HAU'

# type train model
UPLOAD_MODEL = 'UPLOAD_MODEL'
PREDICT_MODEL = 'PREDICT_MODEL'
SELF_TRAIN_MODEL = 'SELF_TRAIN_MODEL'
AUTO_TRAIN_MODEL = 'AUTO_TRAIN_MODEL'

SYSTEM = 'SYSTEM'

# status model
ERROR = 'ERROR'
SUCCESS = 'SUCCESS'

# type model
CONVERT_TYPE = {
    UPLOAD_MODEL: 'MÔ HÌNH UPLOAD',
    SELF_TRAIN_MODEL: 'TRAIN TRÊN WEB',
    AUTO_TRAIN_MODEL: 'TỰ ĐỘNG TRAIN'
}

# convert type argicultural
CONVERT_ARGICULTURAL = {
    LUA: 'LÚA',
    CAFE: 'CÀ PHÊ',
    CAM: 'CAM',
    XOAI: 'XOÀI',
}

ARIMA = 'ARIMA'
LSTM = 'LSTM'
GRU = 'GRU'
BILSTM = 'BILSTM'
ARIMAX = 'ARIMAX'
VAR = 'VAR'
VARMA = 'VARMA'
BASE_MODEL = 'ARIMA'

AGRICULTURAL_TYPES = [LUA, CAFE, CAM, XOAI]